<?php

namespace DL\FamilytreeBundle\Repository;

/**
 * TreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreeRepository extends \Doctrine\ORM\EntityRepository
{
}
